### ISSUE TITLE
[feature request] Toggle default top-level field-flattening behaviour

### ISSUE THREAD

**Issue by ShadowJonathan** [AS207960/xml-serde#4]
While working on the following struct, my output (and input) was unexpectedly interpreted as flattened at the top-level;

```rs
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename = "domain")]
pub struct Domain {
    pub name: String,
    pub uuid: Uuid,
    pub genid: Option<Uuid>,
    pub title: Option<String>,
    pub description: Option<String>,
    // metadata: (),
    pub os: OperatingSystem,
}
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<name xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"></name>
<uuid xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">00000000-0000-0000-0000-000000000000</uuid>
<genid xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"></genid>
<title xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"></title>
<description xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"></description>
<os xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
```

Maybe something akin to `#[xml(flatten)]` on a top-level structure could toggle the last behaviour on instead.

**Comment by TheEnbyperor** [comment]
This is mostly a limitation of Serde. There is no way to pass through ` #[xml(...)]` to the actual encoder, as all Serde structs have to be generic over ever possible encoder. Additionally its very difficult to differentiate between a top level and other elements, again due to the nature of Serde. 

The solution would be to create a root struct for the XML document as a whole; 
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct XMLMessage {
    pub domain: Domain
}
```

**Comment by ShadowJonathan** [comment]
Ah i see, then i'll close this issue.

Yes, i've worked that workaround, but if its actually impossible to differentiate, then i'll keep using it.
